#!/usr/bin/env python
from lib.dbclass import DataBase, DEFAULT_TAGDB_FNAME
from lib.color import format_color
with DataBase(DEFAULT_TAGDB_FNAME) as db:
    for tag, color in db.get_taglist():
        print(format_color(tag, color))
