#!/usr/bin/env python
from dbclass import DB, db_fname, read_pipe, get_inode
from sys import argv
from pathlib import Path
fnames = read_pipe()
if len(argv) < 2:
    exit()
with DB(db_fname) as db:
    for fname in fnames:
        db.add_tag(get_inode(Path(fname).absolute()), argv[1])
