#!/usr/bin/env python
from lib.dbclass import DataBase, get_inode, check_tagdb, default_tagdb_fname
from lib.ninpipe import Pipe
from sys import argv
from pathlib import Path
if len(argv) < 2:
    exit()
with DataBase(check_tagdb(default_tagdb_fname)) as db:
    for fname in Pipe():
        db.add_tag(get_inode(str(Path(fname).absolute())), argv[1])
