#!/usr/bin/env python
from lib.dbclass import DataBase, default_tagdb_fname, check_tagdb
from lib.color import COLOR, ATTRIBUTE, BG_COLOR, set_color
print('Write tag name in this list')
tag = input()
print('Write one of the new attribute in this list.')
print(' '.join(set_color(attribute=key) + key + set_color('RESET')
               for key in ATTRIBUTE.keys()))
attr = input()
print('Write one of the new color in this list.')
print(' '.join(set_color(color=key) + key + set_color('RESET')
      for key in COLOR.keys()))
color = input()
print('Write one of the new background color in this list.')
print(' '.join(set_color(bg_color=key) + key + set_color('RESET')
               for key in BG_COLOR.keys()))
bgcolor = input()
with DataBase(check_tagdb(default_tagdb_fname)) as db:
    db.set_color(tag, set_color(attr, color, bgcolor))
