#!/usr/bin/env python
from lib.dbclass import DataBase, default_tagdb_fname
print('Write tag name')
tag = input()
print('Write new tag name')
name = input()
with DataBase(default_tagdb_fname) as db:
    db.rename_tag(tag, name)
