#!/usr/bin/env python
from typing import cast
from lib.dbclass import DataBase, default_tagdb_fname, get_inode, check_tagdb
from lib.color import set_color
from lib.ninpipe import Pipe
from pathlib import Path
from os.path import exists

def setup_color(fname: str, color: str) -> str:
    if color is None:
        return fname
    return cast(str, color + fname + set_color('RESET'))

with DataBase(check_tagdb(default_tagdb_fname)) as db:
    for data in Pipe().async_iter():
        fname = data.receive()
        if not fname:
            break
        if exists(fname):
            path = Path(fname).absolute()
            tags = db.inode2tag(get_inode(path))
            ftags = [setup_color(*tag) for tag in tags]
            print(fname, '[', ' '.join(ftags), ']')
